####### Geolite2 ########
GEOLITE:
  LICENCE:
    KEY: ${GEOLITE_LICENCE_KEY}
  ACCOUNTID: ${GEOLITE_ACCOUNTID}

######## CHECK MAIL ########
checkMail:
  key: ${CHECK_MAIL_KEY}
  host: ${CHECK_MAIL_HOST}